### ISSUE TITLE
Date of completion not appearing directly after the x

### ISSUE THREAD

**Issue by 83noit** [VladimirMarkelov/todo_lib#4]
It seems that the library does not fully comply with the todo.txt format when a task is completed.

It does implement [Rule 1](https://github.com/todotxt/todo.txt#rule-1-a-completed-task-starts-with-an-lowercase-x-character-x): 
A task is complete if it starts with an x (case-sensitive and lowercase) followed directly by a space.

But it does not respect [Rule 2](https://github.com/todotxt/todo.txt#rule-2-the-date-of-completion-appears-directly-after-the-x-separated-by-a-space), regarding the position of the completion date and the handling of priority for completed tasks.

```
(A) 2023-08-20 Test #ex_1
x (A) 2023-08-20 2023-08-20 Test #ex_2
x 2023-08-20 2023-08-20 Test #ex_3
x 2023-08-20 2023-08-20 pri:A Test #ex_4
x 2023-08-20 2023-08-20 (A) Test #ex_5
```

Currently a pending task (`ex_1`) is completed by just appending `x ` (`ex_2`), whereas the format seems to expect the completion and creation dates to follow the completion flags, with the priority either deleted (`ex_3`) or transformed in a key:value (`ex_4`). Some apps also support just reordering the priority (`ex_5`).

ttdl is my favourite command line tool for todo.txt (thanks!), but this issue makes files not interoperable with other tools, in particular on surfaces where ttdl is less practical, like mobile phones (e.g. [SwiftoDo](https://swiftodoapp.com)).

Ideally:
1. the library should implement the different completion modes and a default behaviour, for the loss of priority, key:value replacement or reordering of the priority, in both the done and undone functions.
2. ttdl should allow to configure the preferred completion mode.

**Comment by VladimirMarkelov** [comment]
It seems  I missed the Rule#2. Thanks for reporting.

**Comment by VladimirMarkelov** [comment]
Done
